//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0
//----------------------

/* eslint-disable */
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable({ providedIn: 'root' })
export class Client {
  private http: HttpClient;
  private baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

  constructor(
    @Inject(HttpClient) http: HttpClient,
    @Optional() @Inject(API_BASE_URL) baseUrl?: string,
  ) {
    this.http = http;
    this.baseUrl = baseUrl ?? '';
  }

  // ---------------------- USERS API ----------------------

  usersAll(): Observable<UserDto[]> {
    let url_ = this.baseUrl + '/api/Users';
    url_ = url_.replace(/[?&]$/, '');

    const options_: any = {
      observe: 'response',
      responseType: 'blob',
      headers: new HttpHeaders({ Accept: 'application/json' }),
    };

    return this.http.request('get', url_, options_).pipe(
      _observableMergeMap((response_: any) => this.processUsersAll(response_)),
      _observableCatch((response_: any) => {
        if (response_ instanceof HttpResponseBase) {
          try {
            return this.processUsersAll(response_);
          } catch (e) {
            return _observableThrow(e) as Observable<UserDto[]>;
          }
        } else return _observableThrow(response_) as Observable<UserDto[]>;
      }),
    );
  }

  protected processUsersAll(response: HttpResponseBase): Observable<UserDto[]> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : response instanceof Blob
          ? response
          : undefined;

    const headers: any = {};
    response.headers?.keys().forEach((key) => (headers[key] = response.headers.get(key)));

    if (status === 200) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((text) => {
          const data = text ? JSON.parse(text, this.jsonParseReviver) : [];
          const result = Array.isArray(data) ? data.map((item: any) => UserDto.fromJS(item)) : [];
          return _observableOf(result);
        }),
      );
    } else if (status !== 204) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((text) =>
          throwException('Unexpected server error', status, text, headers),
        ),
      );
    }
    return _observableOf<UserDto[]>([]);
  }

  usersGET(id: number): Observable<UserDto> {
    if (id === undefined || id === null) throw new Error("The parameter 'id' must be defined.");

    let url_ = this.baseUrl + '/api/Users/{id}';
    url_ = url_.replace('{id}', encodeURIComponent('' + id));
    url_ = url_.replace(/[?&]$/, '');

    const options_: any = {
      observe: 'response',
      responseType: 'blob',
      headers: new HttpHeaders({ Accept: 'application/json' }),
    };

    return this.http.request('get', url_, options_).pipe(
      _observableMergeMap((response_: any) => this.processUsersGET(response_)),
      _observableCatch((response_: any) => {
        if (response_ instanceof HttpResponseBase) {
          try {
            return this.processUsersGET(response_);
          } catch (e) {
            return _observableThrow(e) as Observable<UserDto>;
          }
        } else return _observableThrow(response_) as Observable<UserDto>;
      }),
    );
  }

  protected processUsersGET(response: HttpResponseBase): Observable<UserDto> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : response instanceof Blob
          ? response
          : undefined;

    const headers: any = {};
    response.headers?.keys().forEach((key) => (headers[key] = response.headers.get(key)));

    if (status === 200) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((text) => {
          const data = text ? JSON.parse(text, this.jsonParseReviver) : undefined;
          return _observableOf(UserDto.fromJS(data));
        }),
      );
    } else if (status !== 204) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((text) =>
          throwException('Unexpected server error', status, text, headers),
        ),
      );
    }
    return _observableOf<UserDto>(undefined!);
  }

  usersPOST(body: UserDto | undefined): Observable<UserDto> {
    const url_ = this.baseUrl + '/api/Users';
    const content_ = JSON.stringify(body);

    const options_: any = {
      body: content_,
      observe: 'response',
      responseType: 'blob',
      headers: new HttpHeaders({ 'Content-Type': 'application/json', Accept: 'application/json' }),
    };

    return this.http.request('post', url_, options_).pipe(
      _observableMergeMap((response_: any) => this.processUsersPOST(response_)),
      _observableCatch((response_: any) => {
        if (response_ instanceof HttpResponseBase) {
          try {
            return this.processUsersPOST(response_);
          } catch (e) {
            return _observableThrow(e) as Observable<UserDto>;
          }
        } else return _observableThrow(response_) as Observable<UserDto>;
      }),
    );
  }

  protected processUsersPOST(response: HttpResponseBase): Observable<UserDto> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : response instanceof Blob
          ? response
          : undefined;

    const headers: any = {};
    response.headers?.keys().forEach((key) => (headers[key] = response.headers.get(key)));

    if (status === 201 || status === 200) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((text) => _observableOf(UserDto.fromJS(text ? JSON.parse(text) : {}))),
      );
    } else {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((text) =>
          throwException('Unexpected server error', status, text, headers),
        ),
      );
    }
  }

  usersPUT(id: number, body: UserDto | undefined): Observable<void> {
    if (id === undefined || id === null) throw new Error("The parameter 'id' must be defined.");

    let url_ = this.baseUrl + '/api/Users/{id}';
    url_ = url_.replace('{id}', encodeURIComponent('' + id));
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);
    const options_: any = {
      body: content_,
      observe: 'response',
      responseType: 'blob',
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
    };

    return this.http.request('put', url_, options_).pipe(
      _observableMergeMap((response_: any) => this.processUsersPUT(response_)),
      _observableCatch((response_: any) => {
        if (response_ instanceof HttpResponseBase) {
          try {
            return this.processUsersPUT(response_);
          } catch (e) {
            return _observableThrow(e) as Observable<void>;
          }
        } else return _observableThrow(response_) as Observable<void>;
      }),
    );
  }

  protected processUsersPUT(response: HttpResponseBase): Observable<void> {
    return _observableOf<void>(undefined!); // simplified for demo, handle 400/404 if needed
  }

  usersDELETE(id: number): Observable<void> {
    if (id === undefined || id === null) throw new Error("The parameter 'id' must be defined.");

    let url_ = this.baseUrl + '/api/Users/{id}';
    url_ = url_.replace('{id}', encodeURIComponent('' + id));
    url_ = url_.replace(/[?&]$/, '');

    const options_: any = {
      observe: 'response',
      responseType: 'blob',
      headers: new HttpHeaders({}),
    };

    return this.http.request('delete', url_, options_).pipe(
      _observableMergeMap((response_: any) => this.processUsersDELETE(response_)),
      _observableCatch((response_: any) => {
        if (response_ instanceof HttpResponseBase) {
          try {
            return this.processUsersDELETE(response_);
          } catch (e) {
            return _observableThrow(e) as Observable<void>;
          }
        } else return _observableThrow(response_) as Observable<void>;
      }),
    );
  }

  protected processUsersDELETE(response: HttpResponseBase): Observable<void> {
    return _observableOf<void>(undefined!);
  }
}

// ---------------------- DTOs & Helpers ----------------------

export class UserDto implements IUserDto {
  id?: number;
  name?: string;
  username?: string;
  email?: string;

  constructor(data?: IUserDto) {
    if (data) Object.assign(this, data);
  }

  static fromJS(data: any): UserDto {
    const result = new UserDto();
    if (data) Object.assign(result, data);
    return result;
  }
}

export interface IUserDto {
  id?: number;
  name?: string;
  username?: string;
  email?: string;
}

export class ProblemDetails {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
  [key: string]: any;
}

export class ApiException extends Error {
  status: number;
  response: string;
  headers: { [key: string]: any };
  result: any;
  protected isApiException = true;

  constructor(message: string, status: number, response: string, headers: any, result: any) {
    super(message);
    this.status = status;
    this.response = response;
    this.headers = headers;
    this.result = result;
  }

  static isApiException(obj: any): obj is ApiException {
    return obj?.isApiException === true;
  }
}

function throwException(
  message: string,
  status: number,
  response: string,
  headers: any,
  result?: any,
): Observable<any> {
  if (result !== null && result !== undefined) return _observableThrow(result);
  return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: Blob | null | undefined): Observable<string> {
  if (!blob) return _observableOf('');
  return new Observable<string>((observer) => {
    const reader = new FileReader();
    reader.onload = () => {
      observer.next(reader.result as string);
      observer.complete();
    };
    reader.onerror = () => observer.error(reader.error);
    reader.readAsText(blob);
  });
}
